services:
  api:
    build:
      context: .
      dockerfile: src/edu-api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - STORAGE_ROOT=/app/.localdata
      - ALLOW_DEV_AUTH_BYPASS=true
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./.localdata:/app/.localdata
  db:
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
