"""remove_azure_search_metadata

Revision ID: 0e495cf580db
Revises: 9d34df6b7fd5
Create Date: 2025-09-27 20:05:45.743642

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0e495cf580db"
down_revision: Union[str, Sequence[str], None] = "9d34df6b7fd5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_segments", "search_indexed")
    op.drop_column("document_segments", "search_indexed_at")
    op.drop_column("documents", "search_indexed")
    op.drop_column("documents", "search_indexed_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents",
        sa.Column(
            "search_indexed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "documents",
        sa.Column("search_indexed", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "document_segments",
        sa.Column(
            "search_indexed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "document_segments",
        sa.Column("search_indexed", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
