"""change_study_plan_content_to_json

Revision ID: 12d284c3be7b
Revises: ca92bac4538c
Create Date: 2025-12-20 22:28:40.358007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12d284c3be7b'
down_revision: Union[str, Sequence[str], None] = 'ca92bac4538c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE study_plans")
    op.alter_column('study_plans', 'content',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False,
               postgresql_using='content::json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_plans', 'content',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
