"""add_study_attempts

Revision ID: 1321101a510b
Revises: 3b970a6bde74
Create Date: 2025-11-02 19:33:12.942868

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1321101a510b"
down_revision: Union[str, Sequence[str], None] = "3b970a6bde74"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "study_attempts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("item_type", sa.String(), nullable=False),
        sa.Column("item_id", sa.String(), nullable=False),
        sa.Column("topic", sa.Text(), nullable=False),
        sa.Column("user_answer", sa.String(), nullable=True),
        sa.Column("correct_answer", sa.Text(), nullable=False),
        sa.Column("was_correct", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_study_attempts_item_id"), "study_attempts", ["item_id"], unique=False
    )
    op.create_index(
        op.f("ix_study_attempts_item_type"),
        "study_attempts",
        ["item_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_study_attempts_project_id"),
        "study_attempts",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_study_attempts_user_id"), "study_attempts", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_study_attempts_user_id"), table_name="study_attempts")
    op.drop_index(op.f("ix_study_attempts_project_id"), table_name="study_attempts")
    op.drop_index(op.f("ix_study_attempts_item_type"), table_name="study_attempts")
    op.drop_index(op.f("ix_study_attempts_item_id"), table_name="study_attempts")
    op.drop_table("study_attempts")
    # ### end Alembic commands ###
