"""add_flashcard_group_study_session_id

Revision ID: 16f073c19d8a
Revises: f265c5459882
Create Date: 2025-12-02 23:07:10.109282

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "16f073c19d8a"
down_revision: Union[str, Sequence[str], None] = "f265c5459882"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flashcard_groups", sa.Column("study_session_id", sa.String(), nullable=True)
    )
    op.create_index(
        op.f("ix_flashcard_groups_study_session_id"),
        "flashcard_groups",
        ["study_session_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "flashcard_groups", "study_sessions", ["study_session_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "flashcard_groups", type_="foreignkey")
    op.drop_index(
        op.f("ix_flashcard_groups_study_session_id"), table_name="flashcard_groups"
    )
    op.drop_column("flashcard_groups", "study_session_id")
    # ### end Alembic commands ###
