"""sync_users_with_supabase_auth

Revision ID: 2935b82f772a
Revises: 8cea1d8eaa62
Create Date: 2025-12-04 21:11:56.034833

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2935b82f772a"
down_revision: Union[str, Sequence[str], None] = "8cea1d8eaa62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_users_supabase_user_id"), table_name="users")
    op.drop_column("users", "supabase_user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("supabase_user_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_index(
        op.f("ix_users_supabase_user_id"), "users", ["supabase_user_id"], unique=True
    )
    op.drop_column("users", "updated_at")
    # ### end Alembic commands ###
