"""remove_spaced_repetition

Revision ID: 339047046f57
Revises: fe3d026f4c75
Create Date: 2025-12-07 08:34:31.016886

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "339047046f57"
down_revision: Union[str, Sequence[str], None] = "fe3d026f4c75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_flashcard_spaced_repetition_flashcard_id"),
        table_name="flashcard_spaced_repetition",
    )
    op.drop_index(
        op.f("ix_flashcard_spaced_repetition_group_id"),
        table_name="flashcard_spaced_repetition",
    )
    op.drop_index(
        op.f("ix_flashcard_spaced_repetition_project_id"),
        table_name="flashcard_spaced_repetition",
    )
    op.drop_index(
        op.f("ix_flashcard_spaced_repetition_user_id"),
        table_name="flashcard_spaced_repetition",
    )
    op.drop_table("flashcard_spaced_repetition")
    op.drop_column("flashcard_groups", "spaced_repetition_enabled")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flashcard_groups",
        sa.Column(
            "spaced_repetition_enabled",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_table(
        "flashcard_spaced_repetition",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("flashcard_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("group_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("project_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "ease_factor",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("interval_days", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "repetition_count", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "last_reviewed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "next_review_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["flashcard_id"],
            ["flashcards.id"],
            name=op.f("flashcard_spaced_repetition_flashcard_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["flashcard_groups.id"],
            name=op.f("flashcard_spaced_repetition_group_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("flashcard_spaced_repetition_project_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("flashcard_spaced_repetition_user_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("flashcard_spaced_repetition_pkey")),
    )
    op.create_index(
        op.f("ix_flashcard_spaced_repetition_user_id"),
        "flashcard_spaced_repetition",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flashcard_spaced_repetition_project_id"),
        "flashcard_spaced_repetition",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flashcard_spaced_repetition_group_id"),
        "flashcard_spaced_repetition",
        ["group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flashcard_spaced_repetition_flashcard_id"),
        "flashcard_spaced_repetition",
        ["flashcard_id"],
        unique=False,
    )
    # ### end Alembic commands ###
