"""add_ondelete_cascade

Revision ID: 359f1c1a7f5c
Revises: 339047046f57
Create Date: 2025-12-08 22:58:46.236056

"""

from collections.abc import Sequence
from typing import Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "359f1c1a7f5c"
down_revision: Union[str, Sequence[str], None] = "339047046f57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("chats_user_id_fkey"), "chats", type_="foreignkey")
    op.drop_constraint(op.f("chats_project_id_fkey"), "chats", type_="foreignkey")
    op.create_foreign_key(
        None, "chats", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "chats", "projects", ["project_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("document_segments_document_id_fkey"),
        "document_segments",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "document_segments",
        "documents",
        ["document_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("documents_project_id_fkey"), "documents", type_="foreignkey"
    )
    op.drop_constraint(op.f("documents_owner_id_fkey"), "documents", type_="foreignkey")
    op.create_foreign_key(
        None, "documents", "users", ["owner_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "documents", "projects", ["project_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("flashcard_groups_project_id_fkey"), "flashcard_groups", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("flashcard_groups_study_session_id_fkey"),
        "flashcard_groups",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "flashcard_groups",
        "study_sessions",
        ["study_session_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "flashcard_groups", "projects", ["project_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("flashcard_progress_user_id_fkey"),
        "flashcard_progress",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("flashcard_progress_group_id_fkey"),
        "flashcard_progress",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("flashcard_progress_project_id_fkey"),
        "flashcard_progress",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("flashcard_progress_flashcard_id_fkey"),
        "flashcard_progress",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "flashcard_progress",
        "flashcards",
        ["flashcard_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "flashcard_progress", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "flashcard_progress",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "flashcard_progress",
        "flashcard_groups",
        ["group_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("flashcards_group_id_fkey"), "flashcards", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("flashcards_project_id_fkey"), "flashcards", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "flashcards", "flashcard_groups", ["group_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "flashcards", "projects", ["project_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("mind_maps_project_id_fkey"), "mind_maps", type_="foreignkey"
    )
    op.drop_constraint(op.f("mind_maps_user_id_fkey"), "mind_maps", type_="foreignkey")
    op.create_foreign_key(
        None, "mind_maps", "projects", ["project_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "mind_maps", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("notes_project_id_fkey"), "notes", type_="foreignkey")
    op.create_foreign_key(
        None, "notes", "projects", ["project_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("practice_records_user_id_fkey"), "practice_records", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("practice_records_project_id_fkey"), "practice_records", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "practice_records", "projects", ["project_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "practice_records", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("projects_owner_id_fkey"), "projects", type_="foreignkey")
    op.create_foreign_key(
        None, "projects", "users", ["owner_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("quiz_questions_project_id_fkey"), "quiz_questions", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("quiz_questions_quiz_id_fkey"), "quiz_questions", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "quiz_questions", "quizzes", ["quiz_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "quiz_questions", "projects", ["project_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("quizzes_project_id_fkey"), "quizzes", type_="foreignkey")
    op.create_foreign_key(
        None, "quizzes", "projects", ["project_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("study_sessions_user_id_fkey"), "study_sessions", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("study_sessions_project_id_fkey"), "study_sessions", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "study_sessions", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "study_sessions", "projects", ["project_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("user_usage_user_id_fkey"), "user_usage", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "user_usage", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_usage", type_="foreignkey")
    op.create_foreign_key(
        op.f("user_usage_user_id_fkey"), "user_usage", "users", ["user_id"], ["id"]
    )
    op.drop_constraint(None, "study_sessions", type_="foreignkey")
    op.drop_constraint(None, "study_sessions", type_="foreignkey")
    op.create_foreign_key(
        op.f("study_sessions_project_id_fkey"),
        "study_sessions",
        "projects",
        ["project_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("study_sessions_user_id_fkey"),
        "study_sessions",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(None, "quizzes", type_="foreignkey")
    op.create_foreign_key(
        op.f("quizzes_project_id_fkey"), "quizzes", "projects", ["project_id"], ["id"]
    )
    op.drop_constraint(None, "quiz_questions", type_="foreignkey")
    op.drop_constraint(None, "quiz_questions", type_="foreignkey")
    op.create_foreign_key(
        op.f("quiz_questions_quiz_id_fkey"),
        "quiz_questions",
        "quizzes",
        ["quiz_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("quiz_questions_project_id_fkey"),
        "quiz_questions",
        "projects",
        ["project_id"],
        ["id"],
    )
    op.drop_constraint(None, "projects", type_="foreignkey")
    op.create_foreign_key(
        op.f("projects_owner_id_fkey"), "projects", "users", ["owner_id"], ["id"]
    )
    op.drop_constraint(None, "practice_records", type_="foreignkey")
    op.drop_constraint(None, "practice_records", type_="foreignkey")
    op.create_foreign_key(
        op.f("practice_records_project_id_fkey"),
        "practice_records",
        "projects",
        ["project_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("practice_records_user_id_fkey"),
        "practice_records",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(None, "notes", type_="foreignkey")
    op.create_foreign_key(
        op.f("notes_project_id_fkey"), "notes", "projects", ["project_id"], ["id"]
    )
    op.drop_constraint(None, "mind_maps", type_="foreignkey")
    op.drop_constraint(None, "mind_maps", type_="foreignkey")
    op.create_foreign_key(
        op.f("mind_maps_user_id_fkey"), "mind_maps", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("mind_maps_project_id_fkey"),
        "mind_maps",
        "projects",
        ["project_id"],
        ["id"],
    )
    op.drop_constraint(None, "flashcards", type_="foreignkey")
    op.drop_constraint(None, "flashcards", type_="foreignkey")
    op.create_foreign_key(
        op.f("flashcards_project_id_fkey"),
        "flashcards",
        "projects",
        ["project_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("flashcards_group_id_fkey"),
        "flashcards",
        "flashcard_groups",
        ["group_id"],
        ["id"],
    )
    op.drop_constraint(None, "flashcard_progress", type_="foreignkey")
    op.drop_constraint(None, "flashcard_progress", type_="foreignkey")
    op.drop_constraint(None, "flashcard_progress", type_="foreignkey")
    op.drop_constraint(None, "flashcard_progress", type_="foreignkey")
    op.create_foreign_key(
        op.f("flashcard_progress_flashcard_id_fkey"),
        "flashcard_progress",
        "flashcards",
        ["flashcard_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("flashcard_progress_project_id_fkey"),
        "flashcard_progress",
        "projects",
        ["project_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("flashcard_progress_group_id_fkey"),
        "flashcard_progress",
        "flashcard_groups",
        ["group_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("flashcard_progress_user_id_fkey"),
        "flashcard_progress",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(None, "flashcard_groups", type_="foreignkey")
    op.drop_constraint(None, "flashcard_groups", type_="foreignkey")
    op.create_foreign_key(
        op.f("flashcard_groups_study_session_id_fkey"),
        "flashcard_groups",
        "study_sessions",
        ["study_session_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("flashcard_groups_project_id_fkey"),
        "flashcard_groups",
        "projects",
        ["project_id"],
        ["id"],
    )
    op.drop_constraint(None, "documents", type_="foreignkey")
    op.drop_constraint(None, "documents", type_="foreignkey")
    op.create_foreign_key(
        op.f("documents_owner_id_fkey"), "documents", "users", ["owner_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("documents_project_id_fkey"),
        "documents",
        "projects",
        ["project_id"],
        ["id"],
    )
    op.drop_constraint(None, "document_segments", type_="foreignkey")
    op.create_foreign_key(
        op.f("document_segments_document_id_fkey"),
        "document_segments",
        "documents",
        ["document_id"],
        ["id"],
    )
    op.drop_constraint(None, "chats", type_="foreignkey")
    op.drop_constraint(None, "chats", type_="foreignkey")
    op.create_foreign_key(
        op.f("chats_project_id_fkey"), "chats", "projects", ["project_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("chats_user_id_fkey"), "chats", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
