"""add_summary_remove_pagination

Revision ID: 3b970a6bde74
Revises: 6ca712704290
Create Date: 2025-10-17 22:24:31.773403

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3b970a6bde74"
down_revision: Union[str, Sequence[str], None] = "6ca712704290"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_segments", "segment_order")
    op.drop_column("document_segments", "page_number")
    op.add_column("documents", sa.Column("summary", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "summary")
    op.add_column(
        "document_segments",
        sa.Column("page_number", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "document_segments",
        sa.Column("segment_order", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
