"""add_language_code_to_project

Revision ID: 43ddc48af9ac
Revises: 1cdb205d42a9
Create Date: 2025-09-27 21:17:28.980816

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "43ddc48af9ac"
down_revision: Union[str, Sequence[str], None] = "1cdb205d42a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("language_code", sa.String(), nullable=False, server_default="en"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "language_code")
    # ### end Alembic commands ###
