"""add_azure_entra_fields_to_user

Revision ID: 449119d9b2ee
Revises: b8c07ad41090
Create Date: 2025-10-10 11:43:06.943832

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "449119d9b2ee"
down_revision: Union[str, Sequence[str], None] = "b8c07ad41090"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.String(), nullable=True))
    op.add_column("users", sa.Column("azure_oid", sa.String(), nullable=True))
    op.create_index(op.f("ix_users_azure_oid"), "users", ["azure_oid"], unique=True)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_azure_oid"), table_name="users")
    op.drop_column("users", "azure_oid")
    op.drop_column("users", "email")
    # ### end Alembic commands ###
