"""add_flashcard_spaced_repetition

Revision ID: 67db11805af5
Revises: 85886f577779
Create Date: 2025-12-02 22:27:23.260556

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "67db11805af5"
down_revision: Union[str, Sequence[str], None] = "85886f577779"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flashcard_spaced_repetition",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("flashcard_id", sa.String(), nullable=False),
        sa.Column("group_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("ease_factor", sa.Float(), nullable=False),
        sa.Column("interval_days", sa.Integer(), nullable=False),
        sa.Column("repetition_count", sa.Integer(), nullable=False),
        sa.Column("last_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_review_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["flashcard_id"],
            ["flashcards.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["flashcard_groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_flashcard_spaced_repetition_flashcard_id"),
        "flashcard_spaced_repetition",
        ["flashcard_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flashcard_spaced_repetition_group_id"),
        "flashcard_spaced_repetition",
        ["group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flashcard_spaced_repetition_project_id"),
        "flashcard_spaced_repetition",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flashcard_spaced_repetition_user_id"),
        "flashcard_spaced_repetition",
        ["user_id"],
        unique=False,
    )
    op.add_column(
        "flashcard_groups",
        sa.Column("spaced_repetition_enabled", sa.Boolean(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("flashcard_groups", "spaced_repetition_enabled")
    op.drop_index(
        op.f("ix_flashcard_spaced_repetition_user_id"),
        table_name="flashcard_spaced_repetition",
    )
    op.drop_index(
        op.f("ix_flashcard_spaced_repetition_project_id"),
        table_name="flashcard_spaced_repetition",
    )
    op.drop_index(
        op.f("ix_flashcard_spaced_repetition_group_id"),
        table_name="flashcard_spaced_repetition",
    )
    op.drop_index(
        op.f("ix_flashcard_spaced_repetition_flashcard_id"),
        table_name="flashcard_spaced_repetition",
    )
    op.drop_table("flashcard_spaced_repetition")
    # ### end Alembic commands ###
