"""Add RAG support fields

Revision ID: 82e63c12156c
Revises: 7ec31a028457
Create Date: 2025-09-27 17:21:09.312780

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "82e63c12156c"
down_revision: Union[str, Sequence[str], None] = "7ec31a028457"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_segments", sa.Column("search_indexed", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "document_segments",
        sa.Column("search_indexed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "documents", sa.Column("search_indexed", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "documents",
        sa.Column("search_indexed_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "search_indexed_at")
    op.drop_column("documents", "search_indexed")
    op.drop_column("document_segments", "search_indexed_at")
    op.drop_column("document_segments", "search_indexed")
    # ### end Alembic commands ###
