"""rename_study_attempt_to_practice_record

Revision ID: 85886f577779
Revises: d81d48f055af
Create Date: 2025-12-02 22:21:48.059944

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "85886f577779"
down_revision: Union[str, Sequence[str], None] = "d81d48f055af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "practice_records",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("item_type", sa.String(), nullable=False),
        sa.Column("item_id", sa.String(), nullable=False),
        sa.Column("topic", sa.Text(), nullable=False),
        sa.Column("user_answer", sa.String(), nullable=True),
        sa.Column("correct_answer", sa.Text(), nullable=False),
        sa.Column("was_correct", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_practice_records_item_id"),
        "practice_records",
        ["item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_practice_records_item_type"),
        "practice_records",
        ["item_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_practice_records_project_id"),
        "practice_records",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_practice_records_user_id"),
        "practice_records",
        ["user_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_study_attempts_item_id"), table_name="study_attempts")
    op.drop_index(op.f("ix_study_attempts_item_type"), table_name="study_attempts")
    op.drop_index(op.f("ix_study_attempts_project_id"), table_name="study_attempts")
    op.drop_index(op.f("ix_study_attempts_user_id"), table_name="study_attempts")
    op.drop_table("study_attempts")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "study_attempts",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("project_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("item_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("item_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("topic", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("user_answer", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("correct_answer", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("was_correct", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("study_attempts_project_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("study_attempts_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("study_attempts_pkey")),
    )
    op.create_index(
        op.f("ix_study_attempts_user_id"), "study_attempts", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_study_attempts_project_id"),
        "study_attempts",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_study_attempts_item_type"),
        "study_attempts",
        ["item_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_study_attempts_item_id"), "study_attempts", ["item_id"], unique=False
    )
    op.drop_index(op.f("ix_practice_records_user_id"), table_name="practice_records")
    op.drop_index(op.f("ix_practice_records_project_id"), table_name="practice_records")
    op.drop_index(op.f("ix_practice_records_item_type"), table_name="practice_records")
    op.drop_index(op.f("ix_practice_records_item_id"), table_name="practice_records")
    op.drop_table("practice_records")
    # ### end Alembic commands ###
