"""add_supabase_user_id_to_user

Revision ID: 8cea1d8eaa62
Revises: 16f073c19d8a
Create Date: 2025-12-04 19:55:35.297800

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8cea1d8eaa62"
down_revision: Union[str, Sequence[str], None] = "16f073c19d8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("supabase_user_id", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_users_supabase_user_id"), "users", ["supabase_user_id"], unique=True
    )
    op.drop_column("users", "azure_oid")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_supabase_user_id"), table_name="users")
    op.drop_column("users", "supabase_user_id")
    op.add_column("users", sa.Column("azure_oid", sa.String(), nullable=True))
    # ### end Alembic commands ###
