"""add_user_usage_tracking

Revision ID: 926e2ba2adbb
Revises: 1321101a510b
Create Date: 2025-11-08 19:59:24.685144

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "926e2ba2adbb"
down_revision: Union[str, Sequence[str], None] = "1321101a510b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_usage",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("chat_messages_today", sa.Integer(), nullable=False),
        sa.Column("flashcard_generations_today", sa.Integer(), nullable=False),
        sa.Column("quiz_generations_today", sa.Integer(), nullable=False),
        sa.Column("document_uploads_today", sa.Integer(), nullable=False),
        sa.Column(
            "last_reset_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_usage_user_id"), "user_usage", ["user_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_usage_user_id"), table_name="user_usage")
    op.drop_table("user_usage")
    # ### end Alembic commands ###
