"""update_embedding_vector_dimensions_to_3072

Revision ID: 9d34df6b7fd5
Revises: a7213490698e
Create Date: 2025-09-27 19:15:46.004696

"""

from collections.abc import Sequence
from typing import Union

from alembic import op
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = "9d34df6b7fd5"
down_revision: Union[str, Sequence[str], None] = "a7213490698e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document_segments",
        "embedding_vector",
        existing_type=Vector(1536),
        type_=Vector(3072),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document_segments",
        "embedding_vector",
        existing_type=Vector(3072),
        type_=Vector(1536),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
