"""add_position_to_quiz_questions

Revision ID: c5ead109f6b6
Revises: eb4a0e7c9374
Create Date: 2025-12-08 23:28:22.916777

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c5ead109f6b6"
down_revision: Union[str, Sequence[str], None] = "eb4a0e7c9374"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first
    op.add_column("quiz_questions", sa.Column("position", sa.Integer(), nullable=True))

    # Update existing quiz questions to have sequential positions based on created_at within each quiz
    connection = op.get_bind()
    connection.execute(
        sa.text("""
        WITH ranked_questions AS (
            SELECT
                id,
                ROW_NUMBER() OVER (PARTITION BY quiz_id ORDER BY created_at ASC) - 1 AS pos
            FROM quiz_questions
        )
        UPDATE quiz_questions
        SET position = ranked_questions.pos
        FROM ranked_questions
        WHERE quiz_questions.id = ranked_questions.id
    """)
    )

    # Now make the column NOT NULL with default
    op.alter_column("quiz_questions", "position", nullable=False, server_default="0")
    op.create_index(
        op.f("ix_quiz_questions_position"), "quiz_questions", ["position"], unique=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quiz_questions_position"), table_name="quiz_questions")
    op.drop_column("quiz_questions", "position")
    # ### end Alembic commands ###
