"""add_mindmap_usage

Revision ID: c6293d1898fc
Revises: c5ead109f6b6
Create Date: 2025-12-15 15:32:09.526867

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c6293d1898fc"
down_revision: Union[str, Sequence[str], None] = "c5ead109f6b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1) Add column as nullable so migration works on existing data
    op.add_column(
        "user_usage",
        sa.Column("mindmap_generations_today", sa.Integer(), nullable=True),
    )
    # 2) Backfill existing rows with 0
    op.execute(
        "UPDATE user_usage SET mindmap_generations_today = 0 WHERE mindmap_generations_today IS NULL"
    )
    # 3) Make column non-nullable
    op.alter_column(
        "user_usage",
        "mindmap_generations_today",
        existing_type=sa.Integer(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_usage", "mindmap_generations_today")
    # ### end Alembic commands ###
