"""add_position_to_flashcards

Revision ID: eb4a0e7c9374
Revises: 359f1c1a7f5c
Create Date: 2025-12-08 23:06:50.561736

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eb4a0e7c9374"
down_revision: Union[str, Sequence[str], None] = "359f1c1a7f5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first
    op.add_column("flashcards", sa.Column("position", sa.Integer(), nullable=True))

    # Update existing flashcards to have sequential positions based on created_at within each group
    connection = op.get_bind()
    connection.execute(
        sa.text("""
        WITH ranked_flashcards AS (
            SELECT
                id,
                ROW_NUMBER() OVER (PARTITION BY group_id ORDER BY created_at ASC) - 1 AS pos
            FROM flashcards
        )
        UPDATE flashcards
        SET position = ranked_flashcards.pos
        FROM ranked_flashcards
        WHERE flashcards.id = ranked_flashcards.id
    """)
    )

    # Now make the column NOT NULL with default
    op.alter_column("flashcards", "position", nullable=False, server_default="0")
    op.create_index(
        op.f("ix_flashcards_position"), "flashcards", ["position"], unique=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_flashcards_position"), table_name="flashcards")
    op.drop_column("flashcards", "position")
    # ### end Alembic commands ###
