"""add_study_sessions

Revision ID: f265c5459882
Revises: 3d089122a173
Create Date: 2025-12-02 22:58:18.509762

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f265c5459882"
down_revision: Union[str, Sequence[str], None] = "3d089122a173"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "study_sessions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("session_data", sa.JSON(), nullable=False),
        sa.Column("estimated_time_minutes", sa.Integer(), nullable=False),
        sa.Column("session_length_minutes", sa.Integer(), nullable=False),
        sa.Column("focus_topics", sa.JSON(), nullable=True),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_study_sessions_project_id"),
        "study_sessions",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_study_sessions_user_id"), "study_sessions", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_study_sessions_user_id"), table_name="study_sessions")
    op.drop_index(op.f("ix_study_sessions_project_id"), table_name="study_sessions")
    op.drop_table("study_sessions")
    # ### end Alembic commands ###
