"""add_flashcard_progress

Revision ID: fe3d026f4c75
Revises: 2935b82f772a
Create Date: 2025-12-07 08:25:31.999125

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fe3d026f4c75"
down_revision: Union[str, Sequence[str], None] = "2935b82f772a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flashcard_progress",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("flashcard_id", sa.String(), nullable=False),
        sa.Column("group_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("correct_count", sa.Integer(), nullable=False),
        sa.Column("incorrect_count", sa.Integer(), nullable=False),
        sa.Column("current_streak", sa.Integer(), nullable=False),
        sa.Column("mastery_level", sa.Integer(), nullable=False),
        sa.Column("is_mastered", sa.Boolean(), nullable=False),
        sa.Column("last_result", sa.Boolean(), nullable=True),
        sa.Column("last_practiced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["flashcard_id"],
            ["flashcards.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["flashcard_groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_flashcard_progress_flashcard_id"),
        "flashcard_progress",
        ["flashcard_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flashcard_progress_group_id"),
        "flashcard_progress",
        ["group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flashcard_progress_project_id"),
        "flashcard_progress",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flashcard_progress_user_id"),
        "flashcard_progress",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_flashcard_progress_user_id"), table_name="flashcard_progress"
    )
    op.drop_index(
        op.f("ix_flashcard_progress_project_id"), table_name="flashcard_progress"
    )
    op.drop_index(
        op.f("ix_flashcard_progress_group_id"), table_name="flashcard_progress"
    )
    op.drop_index(
        op.f("ix_flashcard_progress_flashcard_id"), table_name="flashcard_progress"
    )
    op.drop_table("flashcard_progress")
    # ### end Alembic commands ###
